//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRTest.MVC.Services.MyWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.MyWebService.ISignalRTestService")]
    public interface ISignalRTestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignalRTestService/LongRunningTask", ReplyAction="http://tempuri.org/ISignalRTestService/LongRunningTaskResponse")]
        void LongRunningTask(string ConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignalRTestService/LongRunningTask", ReplyAction="http://tempuri.org/ISignalRTestService/LongRunningTaskResponse")]
        System.Threading.Tasks.Task LongRunningTaskAsync(string ConnectionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignalRTestServiceChannel : SignalRTest.MVC.Services.MyWebService.ISignalRTestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignalRTestServiceClient : System.ServiceModel.ClientBase<SignalRTest.MVC.Services.MyWebService.ISignalRTestService>, SignalRTest.MVC.Services.MyWebService.ISignalRTestService {
        
        public SignalRTestServiceClient() {
        }
        
        public SignalRTestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignalRTestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignalRTestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignalRTestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LongRunningTask(string ConnectionId) {
            base.Channel.LongRunningTask(ConnectionId);
        }
        
        public System.Threading.Tasks.Task LongRunningTaskAsync(string ConnectionId) {
            return base.Channel.LongRunningTaskAsync(ConnectionId);
        }
    }
}
